### ISSUE TITLE
Skimming branches

### ISSUE THREAD

**Issue by alefisico** [scikit-hep/hepconvert#64]
Hi, 
I couldn't attend your talk in CAT, but I saw the slides. I am very interested in your tools since my analysis tries to take some nanooad files and try some simple skimming of the files to make our pipeline faster. Your tool can really simplify our lives. 

- Do you have any example of how can I take an entire dataset (more than one file) remove branches and save a new root file? For this, should I need to run in some sort of computer cluster (like HTCondor), or can I run locally? or with Dask?
- My other suggestion/request is if a simple selection can be included while doing the removal of branches. I am not talking about making an entire analysis selection, but perhaps applying some event flags (like a trigger).

Thanks a lot for the help.

**Comment by alefisico** [comment]
Hi @zbilodea 
thanks for the reply. What I have in mind is something like this. I understand that now you can keep or drop the full branches. Now, in nanoAOD, there are boolean branches, like `HLT_blahblah`. So my question is if you can keep or drop a subset of the full branches based on that boolean condition. Is it more clear? I can try to explain more if you need.

**Comment by NJManganelli** [comment]
Do you mean keep or drop TTree entries based on the per-entry boolean values (skimming), or keep/drop certain branches (slimming) based on which boolean branches are present?

**Comment by alefisico** [comment]
I mean skimming. From what I understand, the current functionality only does slimming (from your definition)

**Comment by zbilodea** [comment]
Ah yes I see now! Thank you for clarifying, I will work on adding skimming!

**Comment by zbilodea** [comment]
I've added an option for branch skimming, it is the keyword argument "cut" (works like Uproot's "cut" parameter in uproot.iterate() and uproot.arrays()). Let me know if there are any changes I could make to improve this or if any issues come up! I'll add examples to the docs soon but here's one for the case you mentioned:
For using an HLT branch and keeping only branches that start with "Photon_":     
```
hepconvert.copy_root(
        "destination.root",
        "nanoAOD_2015_CMS_Open_Data_ttbar.root",
        keep_branches=["Photon_*"],
        force=True,
        cut="HLT_Photon30",
    )
```
